      SUBROUTINE CHEC1A(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  ICH1A)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CHEC1A'
      IF (ICHECK.GE.997) CALL OTRC('CHEC1A','05/15/95')
C
C
C
      ICH1A=0
      DO 100 IEL=1,NEL
C
      ITYP=KNELM(IEL)
      IF (ITYP.EQ.1) GOTO 100
C
      IADJ1=KADJ(1,IEL)
      IADJ2=KADJ(2,IEL)
      IADJ3=KADJ(3,IEL)
      IADJ4=KADJ(4,IEL)
C
      ITYP1=0
      ITYP2=0
      ITYP3=0
      ITYP4=0
      IF (IADJ1.NE.0) ITYP1=KNELM(IADJ1)
      IF (IADJ2.NE.0) ITYP2=KNELM(IADJ2)
      IF (IADJ3.NE.0) ITYP3=KNELM(IADJ3)
      IF (IADJ4.NE.0) ITYP4=KNELM(IADJ4)
      ITYP=ITYP1+ITYP2+ITYP3+ITYP4
      IF (ITYP.GE.3) THEN
       KNELM(IEL)=1
       ICH1A=ICH1A+1
      ENDIF
C
100   CONTINUE
C
      END
C
C *****************************************************************
C
      SUBROUTINE CHEC1B(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  ICH1B)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CHEC1B'
      IF (ICHECK.GE.997) CALL OTRC('CHEC1B','05/15/95')
C
C
C
      ICH1B=0
      DO 100 IEL=1,NEL
C
      ITYP=KNELM(IEL)
      IF (ITYP.EQ.1) THEN
       ICH1B=ICH1B+8
       GOTO 100
      ENDIF
C
      IADJ1=KADJ(1,IEL)
      IADJ2=KADJ(2,IEL)
      IADJ3=KADJ(3,IEL)
      IADJ4=KADJ(4,IEL)
C
      ITYP1=0
      ITYP2=0
      ITYP3=0
      ITYP4=0
      IF (IADJ1.NE.0) ITYP1=KNELM(IADJ1)
      IF (IADJ2.NE.0) ITYP2=KNELM(IADJ2)
      IF (IADJ3.NE.0) ITYP3=KNELM(IADJ3)
      IF (IADJ4.NE.0) ITYP4=KNELM(IADJ4)
      IF (ITYP1.GT.1) ITYP1=0
      IF (ITYP2.GT.1) ITYP2=0
      IF (ITYP3.GT.1) ITYP3=0
      IF (ITYP4.GT.1) ITYP4=0
      ITYP=ITYP1+ITYP2+ITYP3+ITYP4
C
      IF (ITYP.EQ.1) THEN
       KNELM(IEL)=2
       ICH1B=ICH1B+3
      ENDIF
C
      IF (ITYP.EQ.2) THEN
       IF (((ITYP1+ITYP3).EQ.2).OR.((ITYP2+ITYP4).EQ.2)) THEN
        KNELM(IEL)=3
        ICH1B=ICH1B+2
       ELSE
        KNELM(IEL)=4
        ICH1B=ICH1B+4
       ENDIF
      ENDIF
C
100   CONTINUE
C
      END
C
C *****************************************************************
C
      SUBROUTINE CREF1A(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  KINDEL,NELOLD,NVTOLD)
C
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*),KINDEL(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      EXTERNAL PARX,PARY,TMAX
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CREF1A'
      IF (ICHECK.GE.997) CALL OTRC('CREF1A','05/15/95')
C
C
C
      INDIEL=0
      DO 100 IEL=1,NELOLD
C
      ITYP=KNELM(IEL)
      IF (ITYP.NE.1) GOTO 100
C
      INDIEL=INDIEL+1
      KINDEL(IEL)=INDIEL
C
      IVT1=KVERT(1,IEL)
      IVT2=KVERT(2,IEL)
      IVT3=KVERT(3,IEL)
      IVT4=KVERT(4,IEL)
C
      INPR1=KNPR(IVT1)
      INPR2=KNPR(IVT2)
      INPR3=KNPR(IVT3)
      INPR4=KNPR(IVT4)
C
      PX1=DCORVG(1,IVT1)
      PX2=DCORVG(1,IVT2)
      PX3=DCORVG(1,IVT3)
      PX4=DCORVG(1,IVT4)
      PY1=DCORVG(2,IVT1)
      PY2=DCORVG(2,IVT2)
      PY3=DCORVG(2,IVT3)
      PY4=DCORVG(2,IVT4)
C
      CALL XCORI(PX1,PX2,PX3,PX4,PY1,PY2,PY3,PY4,
     *           PXN1,PXN2,PXN3,PXN4,PYN1,PYN2,PYN3,PYN4,
     *           DELMA,DELMB)
C
      IVTN1=NVT+1
      IVTN2=NVT+2
      IVTN3=NVT+3
      IVTN4=NVT+4
C
      DCORVG(1,IVTN1)=PXN1
      DCORVG(2,IVTN1)=PYN1
      DCORVG(1,IVTN2)=PXN2
      DCORVG(2,IVTN2)=PYN2
      DCORVG(1,IVTN3)=PXN3
      DCORVG(2,IVTN3)=PYN3
      DCORVG(1,IVTN4)=PXN4
      DCORVG(2,IVTN4)=PYN4
C
      KNPR(IVTN1)=0
      KNPR(IVTN2)=0
      KNPR(IVTN3)=0
      KNPR(IVTN4)=0
C
      KVERT(1,IEL)=IVTN1
      KVERT(2,IEL)=IVTN2
      KVERT(3,IEL)=IVTN3
      KVERT(4,IEL)=IVTN4
C
      NVT=NVT+4
C
C
      IADJ1=KADJ(1,IEL)
      IADJ2=KADJ(2,IEL)
      IADJ3=KADJ(3,IEL)
      IADJ4=KADJ(4,IEL)
C
      ITYP1=0
      ITYP2=0
      ITYP3=0
      ITYP4=0
      IF (IADJ1.NE.0) ITYP1=KNELM(IADJ1)
      IF (IADJ2.NE.0) ITYP2=KNELM(IADJ2)
      IF (IADJ3.NE.0) ITYP3=KNELM(IADJ3)
      IF (IADJ4.NE.0) ITYP4=KNELM(IADJ4)
C
C
      IF ((ITYP1.EQ.1).AND.(KINDEL(IADJ1).LT.INDIEL)
     *                .AND.(KINDEL(IADJ1).GT.0)) THEN
       DO 110 JADJH=1,4
       IADJH=KADJ(JADJH,IADJ1)
       IF (IADJH.EQ.IEL) GOTO 112
110    CONTINUE
       WRITE(6,*) 'ERROR 1 IN CREF1A'
C
112    IVTS1=KVERT(2,NELOLD+(KINDEL(IADJ1)-1)*8+2*JADJH)
       IVTS2=KVERT(1,NELOLD+(KINDEL(IADJ1)-1)*8+2*JADJH)
       INPRS1=0
      ELSE
       IVTS1=NVT+1
       IVTS2=NVT+2
       CALL XCORS(PX1,PX2,PY1,PY2,PXS1,PXS2,PYS1,PYS2,
     *            INPR1,INPR2,INPRS1,DELMA,DELMB)
       DCORVG(1,IVTS1)=PXS1
       DCORVG(1,IVTS2)=PXS2
       DCORVG(2,IVTS1)=PYS1
       DCORVG(2,IVTS2)=PYS2
       KNPR(IVTS1)=INPRS1
       KNPR(IVTS2)=INPRS1
       NVT=NVT+2
       IF (INPRS1.NE.0) THEN
        CALL XCORSP(DCORVG,DVBDP,KVBD,KMM,NBCT,NVBD,IEL,
     *              IVT1,IVT2,IVTS1,IVTS2,INPR1,INPR2,
     *              DELMA,DELMB,PARX,PARY,TMAX)
       ENDIF
      ENDIF
C
      IF ((ITYP2.EQ.1).AND.(KINDEL(IADJ2).LT.INDIEL)
     *                .AND.(KINDEL(IADJ2).GT.0)) THEN
       DO 120 JADJH=1,4
       IADJH=KADJ(JADJH,IADJ2)
       IF (IADJH.EQ.IEL) GOTO 122
120    CONTINUE
       WRITE(6,*) 'ERROR 2 IN CREF1A'
C
122    IVTS3=KVERT(2,NELOLD+(KINDEL(IADJ2)-1)*8+2*JADJH)
       IVTS4=KVERT(1,NELOLD+(KINDEL(IADJ2)-1)*8+2*JADJH)
       INPRS2=0
      ELSE
       IVTS3=NVT+1
       IVTS4=NVT+2
       CALL XCORS(PX2,PX3,PY2,PY3,PXS3,PXS4,PYS3,PYS4,
     *            INPR2,INPR3,INPRS2,DELMA,DELMB)
       DCORVG(1,IVTS3)=PXS3
       DCORVG(1,IVTS4)=PXS4
       DCORVG(2,IVTS3)=PYS3
       DCORVG(2,IVTS4)=PYS4
       KNPR(IVTS3)=INPRS2
       KNPR(IVTS4)=INPRS2
       NVT=NVT+2
       IF (INPRS2.NE.0) THEN
        CALL XCORSP(DCORVG,DVBDP,KVBD,KMM,NBCT,NVBD,IEL,
     *              IVT2,IVT3,IVTS3,IVTS4,INPR2,INPR3,
     *              DELMA,DELMB,PARX,PARY,TMAX)
       ENDIF
      ENDIF
C
      IF ((ITYP3.EQ.1).AND.(KINDEL(IADJ3).LT.INDIEL)
     *                .AND.(KINDEL(IADJ3).GT.0)) THEN
       DO 130 JADJH=1,4
       IADJH=KADJ(JADJH,IADJ3)
       IF (IADJH.EQ.IEL) GOTO 132
130    CONTINUE
       WRITE(6,*) 'ERROR 3 IN CREF1A'
C
132    IVTS5=KVERT(2,NELOLD+(KINDEL(IADJ3)-1)*8+2*JADJH)
       IVTS6=KVERT(1,NELOLD+(KINDEL(IADJ3)-1)*8+2*JADJH)
       INPRS3=0
      ELSE
       IVTS5=NVT+1
       IVTS6=NVT+2
       CALL XCORS(PX3,PX4,PY3,PY4,PXS5,PXS6,PYS5,PYS6,
     *            INPR3,INPR4,INPRS3,DELMA,DELMB)
       DCORVG(1,IVTS5)=PXS5
       DCORVG(1,IVTS6)=PXS6
       DCORVG(2,IVTS5)=PYS5
       DCORVG(2,IVTS6)=PYS6
       KNPR(IVTS5)=INPRS3
       KNPR(IVTS6)=INPRS3
       NVT=NVT+2
       IF (INPRS3.NE.0) THEN
        CALL XCORSP(DCORVG,DVBDP,KVBD,KMM,NBCT,NVBD,IEL,
     *              IVT3,IVT4,IVTS5,IVTS6,INPR3,INPR4,
     *              DELMA,DELMB,PARX,PARY,TMAX)
       ENDIF
      ENDIF
C
      IF ((ITYP4.EQ.1).AND.(KINDEL(IADJ4).LT.INDIEL)
     *                .AND.(KINDEL(IADJ4).GT.0)) THEN
       DO 140 JADJH=1,4
       IADJH=KADJ(JADJH,IADJ4)
       IF (IADJH.EQ.IEL) GOTO 142
140    CONTINUE
       WRITE(6,*) 'ERROR 4 IN CREF1A'
C
142    IVTS7=KVERT(2,NELOLD+(KINDEL(IADJ4)-1)*8+2*JADJH)
       IVTS8=KVERT(1,NELOLD+(KINDEL(IADJ4)-1)*8+2*JADJH)
       INPRS4=0
      ELSE
       IVTS7=NVT+1
       IVTS8=NVT+2
       CALL XCORS(PX4,PX1,PY4,PY1,PXS7,PXS8,PYS7,PYS8,
     *            INPR4,INPR1,INPRS4,DELMA,DELMB)
       DCORVG(1,IVTS7)=PXS7
       DCORVG(1,IVTS8)=PXS8
       DCORVG(2,IVTS7)=PYS7
       DCORVG(2,IVTS8)=PYS8
       KNPR(IVTS7)=INPRS4
       KNPR(IVTS8)=INPRS4
       NVT=NVT+2
       IF (INPRS4.NE.0) THEN
        CALL XCORSP(DCORVG,DVBDP,KVBD,KMM,NBCT,NVBD,IEL,
     *              IVT4,IVT1,IVTS7,IVTS8,INPR4,INPR1,
     *              DELMA,DELMB,PARX,PARY,TMAX)
       ENDIF
      ENDIF
C
C
      IF ((INPRS1.NE.0).OR.(INPRS3.NE.0)) THEN
       A1=1D0-DELMA
       A2=1D0-A1
       DCORVG(1,IVTN1)=A1*DCORVG(1,IVTS1)+A2*DCORVG(1,IVTS6)
       DCORVG(2,IVTN1)=A1*DCORVG(2,IVTS1)+A2*DCORVG(2,IVTS6)
       DCORVG(1,IVTN4)=A2*DCORVG(1,IVTS1)+A1*DCORVG(1,IVTS6)
       DCORVG(2,IVTN4)=A2*DCORVG(2,IVTS1)+A1*DCORVG(2,IVTS6)
       DCORVG(1,IVTN2)=A1*DCORVG(1,IVTS2)+A2*DCORVG(1,IVTS5)
       DCORVG(2,IVTN2)=A1*DCORVG(2,IVTS2)+A2*DCORVG(2,IVTS5)
       DCORVG(1,IVTN3)=A2*DCORVG(1,IVTS2)+A1*DCORVG(1,IVTS5)
       DCORVG(2,IVTN3)=A2*DCORVG(2,IVTS2)+A1*DCORVG(2,IVTS5)
      ENDIF
C
      IF ((INPRS2.NE.0).OR.(INPRS4.NE.0)) THEN
       A1=1D0-DELMA
       A2=1D0-A1
       DCORVG(1,IVTN1)=A1*DCORVG(1,IVTS8)+A2*DCORVG(1,IVTS3)
       DCORVG(2,IVTN1)=A1*DCORVG(2,IVTS8)+A2*DCORVG(2,IVTS3)
       DCORVG(1,IVTN2)=A2*DCORVG(1,IVTS8)+A1*DCORVG(1,IVTS3)
       DCORVG(2,IVTN2)=A2*DCORVG(2,IVTS8)+A1*DCORVG(2,IVTS3)
       DCORVG(1,IVTN4)=A1*DCORVG(1,IVTS7)+A2*DCORVG(1,IVTS4)
       DCORVG(2,IVTN4)=A1*DCORVG(2,IVTS7)+A2*DCORVG(2,IVTS4)
       DCORVG(1,IVTN3)=A2*DCORVG(1,IVTS7)+A1*DCORVG(1,IVTS4)
       DCORVG(2,IVTN3)=A2*DCORVG(2,IVTS7)+A1*DCORVG(2,IVTS4)
      ENDIF
C
C
      KVERT(1,NEL+1)=IVT1
      KVERT(2,NEL+1)=IVTS1
      KVERT(3,NEL+1)=IVTN1
      KVERT(4,NEL+1)=IVTS8
C
      KVERT(1,NEL+2)=IVTS1
      KVERT(2,NEL+2)=IVTS2
      KVERT(3,NEL+2)=IVTN2
      KVERT(4,NEL+2)=IVTN1
C
      KVERT(1,NEL+3)=IVT2
      KVERT(2,NEL+3)=IVTS3
      KVERT(3,NEL+3)=IVTN2
      KVERT(4,NEL+3)=IVTS2
C
      KVERT(1,NEL+4)=IVTS3
      KVERT(2,NEL+4)=IVTS4
      KVERT(3,NEL+4)=IVTN3
      KVERT(4,NEL+4)=IVTN2
C
      KVERT(1,NEL+5)=IVT3
      KVERT(2,NEL+5)=IVTS5
      KVERT(3,NEL+5)=IVTN3
      KVERT(4,NEL+5)=IVTS4
C
      KVERT(1,NEL+6)=IVTS5
      KVERT(2,NEL+6)=IVTS6
      KVERT(3,NEL+6)=IVTN4
      KVERT(4,NEL+6)=IVTN3
C
      KVERT(1,NEL+7)=IVT4
      KVERT(2,NEL+7)=IVTS7
      KVERT(3,NEL+7)=IVTN4
      KVERT(4,NEL+7)=IVTS6
C
      KVERT(1,NEL+8)=IVTS7
      KVERT(2,NEL+8)=IVTS8
      KVERT(3,NEL+8)=IVTN1
      KVERT(4,NEL+8)=IVTN4
C
C
      NEL=NEL+8
C
100   CONTINUE
C
99999 END
C
C *****************************************************************
C
      SUBROUTINE CREF1B(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  KINDEL,NELOLD,NVTOLD)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*),KINDEL(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CREF1B'
      IF (ICHECK.GE.997) CALL OTRC('CREF1B','05/15/95')
C
C
C
      DO 100 IEL=1,NELOLD
C
      ITYP=KNELM(IEL)
      IF (ITYP.NE.2) GOTO 100
C
      DO 110 JADJ=1,4
      IADJ=KADJ(JADJ,IEL)
      IF (KNELM(IADJ).EQ.1) GOTO 112
110   CONTINUE
      WRITE(6,*) 'ERROR 1 IN CREF1B'
C
112   DO 120 JADJH=1,4
      IADJH=KADJ(JADJH,IADJ)
      IF (IADJH.EQ.IEL) GOTO 122
120   CONTINUE
      WRITE(6,*) 'ERROR 2 IN CREF1B'
C
122   IVTS1=KVERT(2,NELOLD+(KINDEL(IADJ)-1)*8+2*JADJH)
      IVTS2=KVERT(1,NELOLD+(KINDEL(IADJ)-1)*8+2*JADJH)
C
C
      IVT1=KVERT(1,IEL)
      IVT2=KVERT(2,IEL)
      IVT3=KVERT(3,IEL)
      IVT4=KVERT(4,IEL)
C
      IF (JADJ.EQ.1) THEN
       IVTH1=IVT1
       IVTH2=IVT2
       IVTH3=IVT3
       IVTH4=IVT4
      ENDIF
C
      IF (JADJ.EQ.2) THEN
       IVTH1=IVT2
       IVTH2=IVT3
       IVTH3=IVT4
       IVTH4=IVT1
      ENDIF
C
      IF (JADJ.EQ.3) THEN
       IVTH1=IVT3
       IVTH2=IVT4
       IVTH3=IVT1
       IVTH4=IVT2
      ENDIF
C
      IF (JADJ.EQ.4) THEN
       IVTH1=IVT4
       IVTH2=IVT1
       IVTH3=IVT2
       IVTH4=IVT3
      ENDIF
C
      PX1=DCORVG(1,IVTH1)
      PX2=DCORVG(1,IVTH2)
      PX3=DCORVG(1,IVTH3)
      PX4=DCORVG(1,IVTH4)
      PY1=DCORVG(2,IVTH1)
      PY2=DCORVG(2,IVTH2)
      PY3=DCORVG(2,IVTH3)
      PY4=DCORVG(2,IVTH4)
C
      CALL XCORM(PX1,PX2,PX3,PX4,PY1,PY2,PY3,PY4,
     *           PXN1,PXN2,PYN1,PYN2,DELMA,DELMB)
C
      IVTN1=NVT+1
      IVTN2=NVT+2
      NVT=NVT+2
C
      DCORVG(1,IVTN1)=PXN1
      DCORVG(2,IVTN1)=PYN1
      DCORVG(1,IVTN2)=PXN2
      DCORVG(2,IVTN2)=PYN2
C
      KNPR(IVTN1)=0
      KNPR(IVTN2)=0
C
C
      KVERT(1,IEL)=IVTS1
      KVERT(2,IEL)=IVTS2
      KVERT(3,IEL)=IVTN2
      KVERT(4,IEL)=IVTN1
C
      KVERT(1,NEL+1)=IVTH1
      KVERT(2,NEL+1)=IVTS1
      KVERT(3,NEL+1)=IVTN1
      KVERT(4,NEL+1)=IVTH4
C
      KVERT(1,NEL+2)=IVTH2
      KVERT(2,NEL+2)=IVTH3
      KVERT(3,NEL+2)=IVTN2
      KVERT(4,NEL+2)=IVTS2
C
      KVERT(1,NEL+3)=IVTH3
      KVERT(2,NEL+3)=IVTH4
      KVERT(3,NEL+3)=IVTN1
      KVERT(4,NEL+3)=IVTN2
C
      NEL=NEL+3
C
100   CONTINUE
C
99999 END
C
C *****************************************************************
C
      SUBROUTINE CREF1C(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  KINDEL,NELOLD,NVTOLD)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*),KINDEL(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CREF1C'
      IF (ICHECK.GE.997) CALL OTRC('CREF1C','05/15/95')
C
C
C
      DO 100 IEL=1,NELOLD
C
      ITYP=KNELM(IEL)
      IF (ITYP.NE.3) GOTO 100
C
      IVT1=KVERT(1,IEL)
      IVT2=KVERT(2,IEL)
      IVT3=KVERT(3,IEL)
      IVT4=KVERT(4,IEL)
C
      DO 110 JADJ1=1,4
      IADJ1=KADJ(JADJ1,IEL)
      IF (KNELM(IADJ1).EQ.1) GOTO 112
110   CONTINUE
      WRITE(6,*) 'ERROR 1 IN CREF1C'
C
112   DO 120 JADJH1=1,4
      IADJH=KADJ(JADJH1,IADJ1)
      IF (IADJH.EQ.IEL) GOTO 122
120   CONTINUE
      WRITE(6,*) 'ERROR 2 IN CREF1C'
C
122   IVTS1=KVERT(1,NELOLD+(KINDEL(IADJ1)-1)*8+2*JADJH1)
      IVTS2=KVERT(2,NELOLD+(KINDEL(IADJ1)-1)*8+2*JADJH1)
C
C
      JADJ2=MOD(JADJ1+1,4)+1
      IADJ2=KADJ(JADJ2,IEL)
C
      DO 130 JADJH2=1,4
      IADJH=KADJ(JADJH2,IADJ2)
      IF (IADJH.EQ.IEL) GOTO 132
130   CONTINUE
      WRITE(6,*) 'ERROR 3 IN CREF1C'
C
132   IVTS3=KVERT(1,NELOLD+(KINDEL(IADJ2)-1)*8+2*JADJH2)
      IVTS4=KVERT(2,NELOLD+(KINDEL(IADJ2)-1)*8+2*JADJH2)
C
C
      KVERT(1,IEL)=IVTS1
      KVERT(2,IEL)=IVTS4
      KVERT(3,IEL)=IVTS3
      KVERT(4,IEL)=IVTS2
C
C
      IF (JADJ1.EQ.1) THEN
       IVTH1=IVT1
       IVTH2=IVT2
       IVTH3=IVT3
       IVTH4=IVT4
      ENDIF
C
      IF (JADJ1.EQ.2) THEN
       IVTH1=IVT2
       IVTH2=IVT3
       IVTH3=IVT4
       IVTH4=IVT1
      ENDIF
C
      IF (JADJ1.EQ.3) THEN
       IVTH1=IVT3
       IVTH2=IVT4
       IVTH3=IVT1
       IVTH4=IVT2
      ENDIF
C
      IF (JADJ1.EQ.4) THEN
       IVTH1=IVT4
       IVTH2=IVT1
       IVTH3=IVT2
       IVTH4=IVT3
      ENDIF
C
      KVERT(1,NEL+1)=IVTH1
      KVERT(2,NEL+1)=IVTS2
      KVERT(3,NEL+1)=IVTS3
      KVERT(4,NEL+1)=IVTH4
C
      KVERT(1,NEL+2)=IVTH3
      KVERT(2,NEL+2)=IVTS4
      KVERT(3,NEL+2)=IVTS1
      KVERT(4,NEL+2)=IVTH2
C
      NEL=NEL+2
C
100   CONTINUE
C
99999 END
C
C *****************************************************************
C
      SUBROUTINE CREF1D(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  KINDEL,NELOLD,NVTOLD)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*),KINDEL(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CREF1D'
      IF (ICHECK.GE.997) CALL OTRC('CREF1D','05/15/95')
C
C
C
      DO 100 IEL=1,NELOLD
C
      ITYP=KNELM(IEL)
      IF (ITYP.NE.4) GOTO 100
C
      JADS1=1
102   DO 110 JADJ1=JADS1,4
      IADJ1=KADJ(JADJ1,IEL)
      IF (KNELM(IADJ1).EQ.1) GOTO 112
110   CONTINUE
      WRITE(6,*) 'ERROR 1 IN CREF1D'
C
112   DO 120 JADJH1=1,4
      IADJH=KADJ(JADJH1,IADJ1)
      IF (IADJH.EQ.IEL) GOTO 122
120   CONTINUE
      WRITE(6,*) 'ERROR 2 IN CREF1D'
C
122   IVTS1=KVERT(1,NELOLD+(KINDEL(IADJ1)-1)*8+2*JADJH1)
      IVTS2=KVERT(2,NELOLD+(KINDEL(IADJ1)-1)*8+2*JADJH1)
C
C
      JADJ2=MOD(JADJ1,4)+1
      IADJ2=KADJ(JADJ2,IEL)
C
      IF (KNELM(IADJ2).NE.1) THEN
       JADS1=JADJ1+1
       GOTO 102
      ENDIF
C
      DO 130 JADJH2=1,4
      IADJH=KADJ(JADJH2,IADJ2)
      IF (IADJH.EQ.IEL) GOTO 132
130   CONTINUE
      WRITE(6,*) 'ERROR 3 IN CREF1D'
C
132   IVTS3=KVERT(1,NELOLD+(KINDEL(IADJ2)-1)*8+2*JADJH2)
      IVTS4=KVERT(2,NELOLD+(KINDEL(IADJ2)-1)*8+2*JADJH2)
C
C
      IVT1=KVERT(1,IEL)
      IVT2=KVERT(2,IEL)
      IVT3=KVERT(3,IEL)
      IVT4=KVERT(4,IEL)
C
      IF (JADJ1.EQ.1) THEN
       IVTH1=IVT2
       IVTH2=IVT3
       IVTH3=IVT4
       IVTH4=IVT1
      ENDIF
C
      IF (JADJ1.EQ.2) THEN
       IVTH1=IVT3
       IVTH2=IVT4
       IVTH3=IVT1
       IVTH4=IVT2
      ENDIF
C
      IF (JADJ1.EQ.3) THEN
       IVTH1=IVT4
       IVTH2=IVT1
       IVTH3=IVT2
       IVTH4=IVT3
      ENDIF
C
      IF (JADJ1.EQ.4) THEN
       IVTH1=IVT1
       IVTH2=IVT2
       IVTH3=IVT3
       IVTH4=IVT4
      ENDIF
C
      PX1=DCORVG(1,IVTH1)
      PX2=DCORVG(1,IVTH2)
      PX3=DCORVG(1,IVTH3)
      PX4=DCORVG(1,IVTH4)
      PY1=DCORVG(2,IVTH1)
      PY2=DCORVG(2,IVTH2)
      PY3=DCORVG(2,IVTH3)
      PY4=DCORVG(2,IVTH4)
C
      CALL XCORI(PX1,PX2,PX3,PX4,PY1,PY2,PY3,PY4,
     *           PXN1,PXN2,PXN3,PXN4,PYN1,PYN2,PYN3,PYN4,
     *           DELMA,DELMB)
C
      IVTN1=NVT+1
      IVTN2=NVT+2
      NVT=NVT+2
C
      DCORVG(1,IVTN1)=PXN1
      DCORVG(2,IVTN1)=PYN1
      DCORVG(1,IVTN2)=PXN3
      DCORVG(2,IVTN2)=PYN3
C
      KNPR(IVTN1)=0
      KNPR(IVTN2)=0
C
C
      KVERT(1,IEL)=IVTH1
      KVERT(2,IEL)=IVTS4
      KVERT(3,IEL)=IVTN1
      KVERT(4,IEL)=IVTS1
C
      KVERT(1,NEL+1)=IVTS4
      KVERT(2,NEL+1)=IVTS3
      KVERT(3,NEL+1)=IVTN2
      KVERT(4,NEL+1)=IVTN1
C
      KVERT(1,NEL+2)=IVTS2
      KVERT(2,NEL+2)=IVTS1
      KVERT(3,NEL+2)=IVTN1
      KVERT(4,NEL+2)=IVTN2
C
      KVERT(1,NEL+3)=IVTS3
      KVERT(2,NEL+3)=IVTH2
      KVERT(3,NEL+3)=IVTH3
      KVERT(4,NEL+3)=IVTN2
C
      KVERT(1,NEL+4)=IVTS2
      KVERT(2,NEL+4)=IVTN2
      KVERT(3,NEL+4)=IVTH3
      KVERT(4,NEL+4)=IVTH4
C
      NEL=NEL+4
C
100   CONTINUE
C
99999 END
