      SUBROUTINE CHEC6A(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  ICH6A)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CHEC6A'
      IF (ICHECK.GE.997) CALL OTRC('CHEC6A','05/15/95')
C
C
C
      ICH6A=0
      DO 100 IEL=1,NEL
C
      ITYP=KNELM(IEL)
      IF (ITYP.NE.20) GOTO 100
C
      IADJ1=KADJ(1,IEL)
      IADJ2=KADJ(2,IEL)
      IADJ3=KADJ(3,IEL)
      IADJ4=KADJ(4,IEL)
C
      NADJ0=0
      IF (IADJ1.EQ.0) NADJ0=NADJ0+1
      IF (IADJ2.EQ.0) NADJ0=NADJ0+1
      IF (IADJ3.EQ.0) NADJ0=NADJ0+1
      IF (IADJ4.EQ.0) NADJ0=NADJ0+1
C
      IF (NADJ0.NE.2) THEN
       WRITE(6,*) 'ELEMENT ',IEL,' CANCELLED FROM LIST IN CHEC6A'
       KNELM(IEL)=0
      ELSE
       IF (((IADJ1.EQ.0).AND.(IADJ3.EQ.0)).OR.
     *     ((IADJ2.EQ.0).AND.(IADJ4.EQ.0))) THEN
        WRITE(6,*) 'ELEMENT ',IEL,' CANCELLED FROM LIST IN CHEC6A'
       ELSE
        KNELM(IEL)=20
        ICH6A=ICH6A+2
       ENDIF
      ENDIF
C
100   CONTINUE
C
      END
C
C *****************************************************************
C
      SUBROUTINE CREF6A(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  KINDEL,NELOLD,NVTOLD)
C
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*),KINDEL(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      EXTERNAL PARX,PARY,TMAX
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CREF6A'
      IF (ICHECK.GE.997) CALL OTRC('CREF6A','05/15/95')
C
C
C
      DO 100 IEL=1,NELOLD
C
      ITYP=KNELM(IEL)
      IF (ITYP.NE.20) GOTO 100
C
      JADS1=1
102   DO 110 JADJ1=JADS1,4
      IADJ1=KADJ(JADJ1,IEL)
      IF (IADJ1.EQ.0) GOTO 112
110   CONTINUE
      WRITE(6,*) 'ERROR 1 IN CREF6A'
C
112   JADJ2=MOD(JADJ1,4)+1
      IADJ2=KADJ(JADJ2,IEL)
C
      IF (IADJ2.NE.0) THEN
       JADS1=JADJ1+1
       GOTO 102
      ENDIF
C
C
      IVT1=KVERT(1,IEL)
      IVT2=KVERT(2,IEL)
      IVT3=KVERT(3,IEL)
      IVT4=KVERT(4,IEL)
C
      IF (JADJ1.EQ.1) THEN
       IVTH1=IVT2
       IVTH2=IVT3
       IVTH3=IVT4
       IVTH4=IVT1
      ENDIF
C
      IF (JADJ1.EQ.2) THEN
       IVTH1=IVT3
       IVTH2=IVT4
       IVTH3=IVT1
       IVTH4=IVT2
      ENDIF
C
      IF (JADJ1.EQ.3) THEN
       IVTH1=IVT4
       IVTH2=IVT1
       IVTH3=IVT2
       IVTH4=IVT3
      ENDIF
C
      IF (JADJ1.EQ.4) THEN
       IVTH1=IVT1
       IVTH2=IVT2
       IVTH3=IVT3
       IVTH4=IVT4
      ENDIF
C
      INPR1=KNPR(IVTH1)
      INPR2=KNPR(IVTH2)
      INPR3=KNPR(IVTH3)
      INPR4=KNPR(IVTH4)
C
      PX1=DCORVG(1,IVTH1)
      PX2=DCORVG(1,IVTH2)
      PX3=DCORVG(1,IVTH3)
      PX4=DCORVG(1,IVTH4)
      PY1=DCORVG(2,IVTH1)
      PY2=DCORVG(2,IVTH2)
      PY3=DCORVG(2,IVTH3)
      PY4=DCORVG(2,IVTH4)
C
      CALL XCORI(PX1,PX2,PX3,PX4,PY1,PY2,PY3,PY4,
     *           PXN1,PXN2,PXN3,PXN4,PYN1,PYN2,PYN3,PYN4,
     *           DELMA,DELMB)
C
      IVTN1=NVT+1
      NVT=NVT+1
C
      DCORVG(1,IVTN1)=PXN1
      DCORVG(2,IVTN1)=PYN1
      KNPR(IVTN1)=0
C
C
      IVTS4=NVT+1
      IVTSH=NVT+2
      CALL XCORS(PX1,PX4,PY1,PY4,PXS1,PXS2,PYS1,PYS2,
     *           INPR1,INPR4,INPRS1,DELMA,1D0-DELMA)
      DCORVG(1,IVTS4)=PXS1
      DCORVG(2,IVTS4)=PYS1
      KNPR(IVTS4)=INPRS1
      NVT=NVT+1
      CALL XCORSP(DCORVG,DVBDP,KVBD,KMM,NBCT,NVBD,IEL,
     *            IVTH1,IVTH4,IVTS4,IVTSH,INPR1,INPR4,
     *            DELMA,1D0-DELMA,PARX,PARY,TMAX)
      NVBD=NVBD-1
C
      IVTS1=NVT+1
      IVTSH=NVT+2
      CALL XCORS(PX1,PX2,PY1,PY2,PXS1,PXS2,PYS1,PYS2,
     *           INPR1,INPR2,INPRS1,DELMA,1D0-DELMA)
      DCORVG(1,IVTS1)=PXS1
      DCORVG(2,IVTS1)=PYS1
      KNPR(IVTS1)=INPRS1
      NVT=NVT+1
      CALL XCORSP(DCORVG,DVBDP,KVBD,KMM,NBCT,NVBD,IEL,
     *            IVTH1,IVTH2,IVTS1,IVTSH,INPR1,INPR2,
     *            DELMA,1D0-DELMA,PARX,PARY,TMAX)
      NVBD=NVBD-1
C
C
      KVERT(1,IEL)=IVTH1
      KVERT(2,IEL)=IVTS1
      KVERT(3,IEL)=IVTN1
      KVERT(4,IEL)=IVTS4
C
      KVERT(1,NEL+1)=IVTS1
      KVERT(2,NEL+1)=IVTH2
      KVERT(3,NEL+1)=IVTH3
      KVERT(4,NEL+1)=IVTN1
C
      KVERT(1,NEL+2)=IVTS4
      KVERT(2,NEL+2)=IVTN1
      KVERT(3,NEL+2)=IVTH3
      KVERT(4,NEL+2)=IVTH4
C
      NEL=NEL+2
C
100   CONTINUE
C
99999 END
