      SUBROUTINE CHEC4A(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  ICH5A)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CHEC4A'
      IF (ICHECK.GE.997) CALL OTRC('CHEC4A','05/15/95')
C
C
C
      ICH2A=0
      DO 100 IEL=1,NEL
C
      ITYP=KNELM(IEL)
      IF (ITYP.NE.1) GOTO 100
C
      IADJ1=KADJ(1,IEL)
      IADJ2=KADJ(2,IEL)
      IADJ3=KADJ(3,IEL)
      IADJ4=KADJ(4,IEL)
C
      NADJ0=0
      IF (IADJ1.EQ.0) NADJ0=NADJ0+1
      IF (IADJ2.EQ.0) NADJ0=NADJ0+1
      IF (IADJ3.EQ.0) NADJ0=NADJ0+1
      IF (IADJ4.EQ.0) NADJ0=NADJ0+1
C
      IF (NADJ0.NE.1) THEN
       WRITE(6,*) 'ELEMENT ',IEL,' CANCELLED FROM LIST IN CHEC4A'
       KNELM(IEL)=0
       ICH5A=ICH5A+1
      ENDIF
C
100   CONTINUE
C
      END
C
C *****************************************************************
C
      SUBROUTINE CHEC4B(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  ICH5B)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CHEC4B'
      IF (ICHECK.GE.997) CALL OTRC('CHEC4B','05/15/95')
C
C
C
      ICH5B=0
      DO 100 IEL=1,NEL
C
      ITYP=KNELM(IEL)
      IF (ITYP.EQ.1) THEN
       ICH5B=ICH5B+2
       GOTO 100
      ENDIF
C
      IADJ1=KADJ(1,IEL)
      IADJ2=KADJ(2,IEL)
      IADJ3=KADJ(3,IEL)
      IADJ4=KADJ(4,IEL)
C
      ITYP1=0
      IF (IADJ1.NE.0) ITYP1=KNELM(IADJ1)
      IF (ITYP1.EQ.1) THEN
       DO 110 JADJ=1,4
       IADJ=KADJ(JADJ,IADJ1)
       IF (IADJ.EQ.0) GOTO 112
110    CONTINUE
       WRITE(6,*) 'ERROR 1 IN CHEC4B'
C
112    JADJ3=MOD(JADJ+1,4)+1
       IADJH3=KADJ(JADJ3,IADJ1)
       IF (IADJH3.NE.IEL) ITYP1=0
      ELSE
       ITYP1=0
      ENDIF
C
      ITYP2=0
      IF (IADJ2.NE.0) ITYP2=KNELM(IADJ2)
      IF (ITYP2.EQ.1) THEN
       DO 120 JADJ=1,4
       IADJ=KADJ(JADJ,IADJ2)
       IF (IADJ.EQ.0) GOTO 122
120    CONTINUE
       WRITE(6,*) 'ERROR 2 IN CHEC4B'
C
122    JADJ3=MOD(JADJ+1,4)+1
       IADJH3=KADJ(JADJ3,IADJ2)
       IF (IADJH3.NE.IEL) ITYP2=0
      ELSE
       ITYP2=0
      ENDIF
C
      ITYP3=0
      IF (IADJ3.NE.0) ITYP3=KNELM(IADJ3)
      IF (ITYP3.EQ.1) THEN
       DO 130 JADJ=1,4
       IADJ=KADJ(JADJ,IADJ3)
       IF (IADJ.EQ.0) GOTO 132
130    CONTINUE
       WRITE(6,*) 'ERROR 3 IN CHEC4B'
C
132    JADJ3=MOD(JADJ+1,4)+1
       IADJH3=KADJ(JADJ3,IADJ3)
       IF (IADJH3.NE.IEL) ITYP3=0
      ELSE
       ITYP3=0
      ENDIF
C
      ITYP4=0
      IF (IADJ4.NE.0) ITYP4=KNELM(IADJ4)
      IF (ITYP4.EQ.1) THEN
       DO 140 JADJ=1,4
       IADJ=KADJ(JADJ,IADJ4)
       IF (IADJ.EQ.0) GOTO 142
140    CONTINUE
       WRITE(6,*) 'ERROR 4 IN CHEC4B'
C
142    JADJ3=MOD(JADJ+1,4)+1
       IADJH3=KADJ(JADJ3,IADJ4)
       IF (IADJH3.NE.IEL) ITYP4=0
      ELSE
       ITYP4=0
      ENDIF
C
      ITYP=ITYP1+ITYP2+ITYP3+ITYP4
C
      IF (ITYP.EQ.1) THEN
       KNELM(IEL)=2
       ICH5B=ICH5B+3
      ENDIF
C
      IF (ITYP.GE.2) THEN
       WRITE(6,*) 'ERROR 5 IN CHEC4B'
      ENDIF
C
100   CONTINUE
C
      END
C
C *****************************************************************
C
      SUBROUTINE CREF4A(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  KINDEL,NELOLD,NVTOLD)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*),KINDEL(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      EXTERNAL PARX,PARY,TMAX
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CREF4A'
      IF (ICHECK.GE.997) CALL OTRC('CREF4A','05/15/95')
C
C
C
      DO 100 IEL=1,NELOLD
C
      ITYP=KNELM(IEL)
      IF (ITYP.NE.1) GOTO 100
C
      DO 105 JADJ=1,4
      IADJ=KADJ(JADJ,IEL)
      IF (IADJ.EQ.0) GOTO 107
105   CONTINUE
      WRITE(6,*) 'ERROR 1 IN CREF4A'
C
107   IVT1=KVERT(1,IEL)
      IVT2=KVERT(2,IEL)
      IVT3=KVERT(3,IEL)
      IVT4=KVERT(4,IEL)
C
      IF (JADJ.EQ.1) THEN
       IVTH1=IVT1
       IVTH2=IVT2
       IVTH3=IVT3
       IVTH4=IVT4
      ENDIF
C
      IF (JADJ.EQ.2) THEN
       IVTH1=IVT2
       IVTH2=IVT3
       IVTH3=IVT4
       IVTH4=IVT1
      ENDIF
C
      IF (JADJ.EQ.3) THEN
       IVTH1=IVT3
       IVTH2=IVT4
       IVTH3=IVT1
       IVTH4=IVT2
      ENDIF
C
      IF (JADJ.EQ.4) THEN
       IVTH1=IVT4
       IVTH2=IVT1
       IVTH3=IVT2
       IVTH4=IVT3
      ENDIF
C
      INPR1=KNPR(IVTH1)
      INPR2=KNPR(IVTH2)
      INPR3=KNPR(IVTH3)
      INPR4=KNPR(IVTH4)
C
      PX1=DCORVG(1,IVTH1)
      PX2=DCORVG(1,IVTH2)
      PX3=DCORVG(1,IVTH3)
      PX4=DCORVG(1,IVTH4)
      PY1=DCORVG(2,IVTH1)
      PY2=DCORVG(2,IVTH2)
      PY3=DCORVG(2,IVTH3)
      PY4=DCORVG(2,IVTH4)
C
      IVTS1=NVT+1
      IVTS2=NVT+2
      CALL XCORS(PX1,PX2,PY1,PY2,PXS1,PXS2,PYS1,PYS2,
     *           INPR1,INPR2,INPRS1,DELMA,DELMB)
      DCORVG(1,IVTS1)=PXS1
      DCORVG(1,IVTS2)=PXS2
      DCORVG(2,IVTS1)=PYS1
      DCORVG(2,IVTS2)=PYS2
      KNPR(IVTS1)=INPRS1
      KNPR(IVTS2)=INPRS1
      NVT=NVT+2
      CALL XCORSP(DCORVG,DVBDP,KVBD,KMM,NBCT,NVBD,IEL,
     *            IVTH1,IVTH2,IVTS1,IVTS2,INPR1,INPR2,
     *            DELMA,DELMB,PARX,PARY,TMAX)
C
      IVTS5=NVT+1
      IVTS6=NVT+2
      CALL XCORS(PX3,PX4,PY3,PY4,PXS5,PXS6,PYS5,PYS6,
     *           INPR3,INPR4,INPRS3,1D0-DELMB,1D0-DELMA)
      DCORVG(1,IVTS5)=PXS5
      DCORVG(1,IVTS6)=PXS6
      DCORVG(2,IVTS5)=PYS5
      DCORVG(2,IVTS6)=PYS6
      KNPR(IVTS5)=INPRS3
      KNPR(IVTS6)=INPRS3
      NVT=NVT+2
C
C
      KVERT(1,IEL)=IVTS1
      KVERT(2,IEL)=IVTS2
      KVERT(3,IEL)=IVTS5
      KVERT(4,IEL)=IVTS6
C
      KVERT(1,NEL+1)=IVTH1
      KVERT(2,NEL+1)=IVTS1
      KVERT(3,NEL+1)=IVTS6
      KVERT(4,NEL+1)=IVTH4
C
      KVERT(1,NEL+2)=IVTH3
      KVERT(2,NEL+2)=IVTS5
      KVERT(3,NEL+2)=IVTS2
      KVERT(4,NEL+2)=IVTH2
C
      NEL=NEL+2
C
100   CONTINUE
C
99999 END
C
C *****************************************************************
C
      SUBROUTINE CREF4B(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,KNELM,
     *                  KINDEL,NELOLD,NVTOLD)

      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4,NNELM=1000)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*),
     *          KNELM(*),KINDEL(*)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      COMMON /ELEMOD/ ITYPEL,NELMOD,DELMA,DELMB,KELMOD(NNELM)
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='CREF4B'
      IF (ICHECK.GE.997) CALL OTRC('CREF4B','05/15/95')
C
C
C
      DO 100 IEL=1,NELOLD
C
      ITYP=KNELM(IEL)
      IF (ITYP.NE.2) GOTO 100
C
      DO 110 JADJ=1,4
      IADJ=KADJ(JADJ,IEL)
      IF (KNELM(IADJ).EQ.1) GOTO 112
110   CONTINUE
      WRITE(6,*) 'ERROR 1 IN CREF4B'
C
112   IVTS1=KVERT(4,IADJ)
      IVTS2=KVERT(3,IADJ)
C
C
      IVT1=KVERT(1,IEL)
      IVT2=KVERT(2,IEL)
      IVT3=KVERT(3,IEL)
      IVT4=KVERT(4,IEL)
C
      IF (JADJ.EQ.1) THEN
       IVTH1=IVT1
       IVTH2=IVT2
       IVTH3=IVT3
       IVTH4=IVT4
      ENDIF
C
      IF (JADJ.EQ.2) THEN
       IVTH1=IVT2
       IVTH2=IVT3
       IVTH3=IVT4
       IVTH4=IVT1
      ENDIF
C
      IF (JADJ.EQ.3) THEN
       IVTH1=IVT3
       IVTH2=IVT4
       IVTH3=IVT1
       IVTH4=IVT2
      ENDIF
C
      IF (JADJ.EQ.4) THEN
       IVTH1=IVT4
       IVTH2=IVT1
       IVTH3=IVT2
       IVTH4=IVT3
      ENDIF
C
      PX1=DCORVG(1,IVTH1)
      PX2=DCORVG(1,IVTH2)
      PX3=DCORVG(1,IVTH3)
      PX4=DCORVG(1,IVTH4)
      PY1=DCORVG(2,IVTH1)
      PY2=DCORVG(2,IVTH2)
      PY3=DCORVG(2,IVTH3)
      PY4=DCORVG(2,IVTH4)
C
      CALL XCORM(PX1,PX2,PX3,PX4,PY1,PY2,PY3,PY4,
     *           PXN1,PXN2,PYN1,PYN2,DELMA,DELMB)
      IVTN1=NVT+1
      IVTN2=NVT+2
      NVT=NVT+2
C
      DCORVG(1,IVTN1)=PXN1
      DCORVG(2,IVTN1)=PYN1
      DCORVG(1,IVTN2)=PXN2
      DCORVG(2,IVTN2)=PYN2
C
      KNPR(IVTN1)=0
      KNPR(IVTN2)=0
C
C
      KVERT(1,IEL)=IVTS1
      KVERT(2,IEL)=IVTS2
      KVERT(3,IEL)=IVTN2
      KVERT(4,IEL)=IVTN1
C
      KVERT(1,NEL+1)=IVTH1
      KVERT(2,NEL+1)=IVTS1
      KVERT(3,NEL+1)=IVTN1
      KVERT(4,NEL+1)=IVTH4
C
      KVERT(1,NEL+2)=IVTH2
      KVERT(2,NEL+2)=IVTH3
      KVERT(3,NEL+2)=IVTN2
      KVERT(4,NEL+2)=IVTS2
C
      KVERT(1,NEL+3)=IVTH3
      KVERT(2,NEL+3)=IVTH4
      KVERT(3,NEL+3)=IVTN1
      KVERT(4,NEL+3)=IVTN2
C
      NEL=NEL+3
C
100   CONTINUE
C
99999 END
