      SUBROUTINE BDRCHK(DCORVG,DVBDP,KVBD,KVERT,KADJ,KNPR,KMM,
     *                  IBDCHK,PARX,PARY,TMAX)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      CHARACTER SUB*6,FMT*15,CPARAM*120
      PARAMETER (NNVE=4)
      DIMENSION DCORVG(2,*),DVBDP(*)
      DIMENSION KVERT(NNVE,*),KADJ(NNVE,*),KNPR(*),KMM(2,*),KVBD(*)
      DIMENSION PMX(4),PMY(4),PTX(4),PTY(4)
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /TRIAD/  NEL,NVT,NMT,NVE,NVEL,NBCT,NVBD
C
      SAVE /OUTPUT/,/ERRCTL/,/CHAR/,/TRIAD/
C
      SUB='BDRCHK'
      IF (ICHECK.GE.997) CALL OTRC('BDRCHK','05/15/95')
C
C
C
      NCHK=IBDCHK
      INDBAD=0
      INDNKV=0
C
      DO 100 IEL=1,NEL
C
      JADS1=1
102   DO 110 JADJ=JADS1,4
      IADJ=KADJ(JADJ,IEL)
      IF (IADJ.EQ.0) GOTO 112
110   CONTINUE
      GOTO 100
C
112   IVE1=JADJ
      IVE2=MOD(IVE1,4)+1
      IVE3=MOD(IVE2,4)+1
      IVE4=MOD(IVE3,4)+1
C
      IVT1=KVERT(IVE1,IEL)
      IVT2=KVERT(IVE2,IEL)
      IVT3=KVERT(IVE3,IEL)
      IVT4=KVERT(IVE4,IEL)
C
      INPR1=KNPR(IVT1)
      INPR2=KNPR(IVT2)
      INPR3=KNPR(IVT3)
      INPR4=KNPR(IVT4)
C
      PX1=DCORVG(1,IVT1)
      PX2=DCORVG(1,IVT2)
      PX3=DCORVG(1,IVT3)
      PX4=DCORVG(1,IVT4)
      PY1=DCORVG(2,IVT1)
      PY2=DCORVG(2,IVT2)
      PY3=DCORVG(2,IVT3)
      PY4=DCORVG(2,IVT4)
C
C
      PMX(1)=0.5D0*(PX2+PX1)
      PMX(2)=0.5D0*(PX3+PX2)
      PMX(3)=0.5D0*(PX4+PX3)
      PMX(4)=0.5D0*(PX1+PX4)
C
      PMY(1)=0.5D0*(PY2+PY1)
      PMY(2)=0.5D0*(PY3+PY2)
      PMY(3)=0.5D0*(PY4+PY3)
      PMY(4)=0.5D0*(PY1+PY4)
C
      PTX(1)= PY2-PY1
      PTX(2)= PY3-PY2
      PTX(3)= PY4-PY3
      PTX(4)= PY1-PY4
C
      PTY(1)=-PX2+PX1
      PTY(2)=-PX3+PX2
      PTY(3)=-PX4+PX3
      PTY(4)=-PX1+PX4
C
C
      IMM1=KMM(1,INPR1)
      IMM2=KMM(2,INPR1)
      IVBMM1=0
      IVBMM2=0
      INMMB=0
      DO 200 IVBD=1,NVBD
      IF (KVBD(IVBD).EQ.IMM1) THEN
       IVBMM1=IVBD
       INMMB=INMMB+1
      ENDIF
      IF (KVBD(IVBD).EQ.IMM2) THEN
       IVBMM2=IVBD
       INMMB=INMMB+1
      ENDIF
      IF (INMMB.EQ.2) GOTO 201
200   CONTINUE
C
201   ICVBD=0
C
      DO 210 IVBD=1,NVBD
      IVT=KVBD(IVBD)
C
      IF (IVT.EQ.IVT1) THEN
       ICVBD=ICVBD+1
       IVBD1=IVBD
      ENDIF
C
      IF (IVT.EQ.IVT2) THEN
       ICVBD=ICVBD+1
       IVBD2=IVBD
      ENDIF
C
      IF (ICVBD.GE.2) GOTO 220
210   CONTINUE
C
220   DPAR1=DVBDP(IVBD1)
      DPAR2=DVBDP(IVBD2)
C
      IF ((IVT1.EQ.KMM(1,INPR1)).AND.
     *    (DPAR2.GT.0.5D0*TMAX(INPR2))) DPAR1=TMAX(INPR1)
      IF ((IVT2.EQ.KMM(1,INPR2)).AND.
     *    (DPAR1.GT.0.5D0*TMAX(INPR1))) DPAR2=TMAX(INPR2)
C
      DPARCK=(DPAR2-DPAR1)/DBLE(NCHK+1)
C
C
      DO 300 ICHK=1,NCHK
      DPAR=DPAR1+DBLE(ICHK)*DPARCK
      PX=PARX(DPAR,INPR1)
      PY=PARY(DPAR,INPR1)
C
      PXM1=PX-PMX(1)
      PXM2=PX-PMX(2)
      PXM3=PX-PMX(3)
      PXM4=PX-PMX(4)
C
      PYM1=PY-PMY(1)
      PYM2=PY-PMY(2)
      PYM3=PY-PMY(3)
      PYM4=PY-PMY(4)
C
      HB1=PXM1*PTX(1)+PYM1*PTY(1)
      HB2=PXM2*PTX(2)+PYM2*PTY(2)
      HB3=PXM3*PTX(3)+PYM3*PTY(3)
      HB4=PXM4*PTX(4)+PYM4*PTY(4)
C
C
      IF ((HB2.GT.0D0).OR.(HB3.GT.0D0).OR.(HB4.GT.0D0)) THEN
       INDBAD=INDBAD+1
       IF (HB2.GT.0D0) THEN
        IND=2
        IVTH1=IVT2
        IVTH2=IVT3
        HB=HB2
       ENDIF
       IF (HB3.GT.0D0) THEN
        IND=3
        IVTH1=IVT3
        IVTH2=IVT4
        HB=HB3
       ENDIF
       IF (HB4.GT.0D0) THEN
        IND=4
        IVTH1=IVT4
        IVTH2=IVT1
        HB=HB4
       ENDIF
       IF (M.GE.2)
     *    WRITE(MPROT,*) '## IEL = ',IEL,IVTH1,IVTH2,ICHK,NCHK
       IF (M.GE.3)
     *     WRITE(6   ,*) '## IEL = ',IEL,IVTH1,IVTH2,ICHK,NCHK
      ELSE
       IF (HB1.GT.0D0) THEN
        INDNKV=INDNKV+1
        IF (M.GE.2)
     *      WRITE(MPROT,*) '## IEL = ',IEL,' BOUNDARY NOT KONVEX'
        IF (M.GE.3)
     *      WRITE(6    ,*) '## IEL = ',IEL,' BOUNDARY NOT KONVEX'
       ENDIF
      ENDIF
C      
300   CONTINUE
C
      IF (JADJ.LT.4) THEN
       JADS1=JADJ+1
       GOTO 102
      ENDIF
C
100   CONTINUE
C
      IF (INDBAD.GE.1) THEN
       IF (M.GE.1) WRITE(MPROT,*) '## BAD ELEMENTS: ',INDBAD
       IF (M.GE.2) WRITE(6    ,*) '## BAD ELEMENTS: ',INDBAD
       IBDCHK=-INDBAD
      ENDIF
C
      IF (INDNKV.GE.1) THEN
       IF (M.GE.1) WRITE(MPROT,*) '## NOT KONVEX ELEMENTS: ',INDNKV
       IF (M.GE.2) WRITE(6    ,*) '## NOT KONVEX ELEMENTS: ',INDNKV
      ENDIF
C
      IF ((INDBAD.GE.1).OR.(INDNKV.GE.1)) THEN
       IF (M.GE.1) WRITE(MPROT,*)
       IF (M.GE.2) WRITE(6    ,*)
      ENDIF
C
C
C
99999 END
